# ID生成器配置
universe:
  id-generator:
    enabled: true
    key-prefix: id_generator
    default-key: id_generator_default
    expire-time: 0
  redisson:
    enabled: true
    # 以下是可选覆盖项，不配就走默认值
    connection-minimum-idle-size: 1
    connection-pool-size: 8
    lock-watchdog-timeout-ms: 30000

spring:
  application:
    name: universe-demo
  redis:
    # 使用 URI 方式（最简单，自动处理 SSL）
    url: rediss://default:AeawAAIncDExMWQ5NjQ5YzY3ZWM0NjIzYTIyMjU4NzVmZmVhYTQ0ZHAxNTkwNTY@sound-condor-59056.upstash.io:6379
    database: 0
    timeout: 3000ms
    # 以下方式需要额外创建配置类手动启用 SSL
#    host: sound-condor-59056.upstash.io
#    port: 6379
#    password: AeawAAIncDExMWQ5NjQ5YzY3ZWM0NjIzYTIyMjU4NzVmZmVhYTQ0ZHAxNTkwNTY  # 从 Upstash 控制台获取
#    database: 0
#    timeout: 3000ms
  # Redis配置（Sentinel模式）
  #  redis:
  #    # Redis Master 密码（用于连接实际的Redis服务器）
  #    password: password
  #    # Sentinel 模式配置
  #    sentinel:
  #      # Sentinel 主节点名称
  #      master: mymaster
  #      # Sentinel 节点列表
  #      nodes: redis-sentinel.test111:16379,redis-sentinel.test222:16379,redis-sentinel.test333:16379
  #      # Sentinel 密码（如果 Sentinel 需要密码）
  #      # password: password
  #    # 数据库索引
  #    database: 14
  #    # 连接超时时间
  #    timeout: 3000ms
  datasource:
    # TiDB Cloud 连接 URL（替换为你的实际值）网址:tidbcloud.com
    url: jdbc:mysql://gateway01.ap-northeast-1.prod.aws.tidbcloud.com:4000/mydb?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2
    username: 2ydooSeWXxBq9u9.root   # 完整的用户名（包含前缀）
    password: xfcxVyOiD9P63Evl
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
#  mail:
#    host: smtp.resend.com
#    port: 587
#    username: resend
#    password: re_SA5kB86m_9G1AUfhHQxaPiZX1VAxTvDxD   # 从环境变量读取 resend.com
#    from: 1576745517@qq.com
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
  mail:
    host: smtp.qq.com
    port: 587
    username: 1576745517@qq.com
    password: wqnvsgwwvwvdjejc
    from: 1576745517@qq.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


#  jpa:
#    hibernate:
#      ddl-auto: update          # 开发阶段自动建表
#    show-sql: true
#    database-platform: org.hibernate.dialect.TiDBDialect   # TiDB 专用方言

mybatis:
  mapper-locations: classpath:mapper/*.xml   # mapper XML 文件位置
  type-aliases-package: cn.xgt.entity




